spring:
  application:
    name: dvdRentalv2
  datasource:
    url: jdbc:postgresql://localhost:5432/dvdRentalv2
    username: postgres
    password: '&`Cqy!D1:GDV'
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 1111

#logging:
#  file:
#    name: logs/myservice.log
#  logback:
#    rollingpolicy:
#      file-name-pattern: logs/myservice.%d{yyyy-MM-dd_HH-mm-ss}.%i.log
#    max-file-size: 100KB
